### PR TITLE
Python3, pep8, and some tests

### PR DESCRIPTION
**Pull request by kwilcox**
I know this is a deprecated library, but I'm trying to work on compliance checker and being tied to python 2.7 isn't going to work

### CODE REVIEW

**Comment by ocefpaf** [comment]
:+1: 

Can we can a new release so I can update the conda recipe?

**Comment by lukecampbell** [comment]
Can someone test the changes and let me know when's it ok to bundle a new release?

**Comment by ocefpaf** [comment]
@kwilcox are you done with this?  If so I can start  typical "boilerplate PR" to add travis, new release, etc.

**Comment by kwilcox** [comment]
I had to run out the door quick... sick kid.  Code works AFAIK, just needs better docs and travis hooked up. I tested py27 and py34 locally.  Someone needs to test it with Wicken and ultimately the compliance checker before we say it works and can release.

**Comment by lukecampbell** [comment]
I can have @danieljmaher test this with compliance checker tomorrow.

**Comment by lukecampbell** [comment]
For CC, we need to abandon this library...

**Comment by ocefpaf** [comment]
> I had to run out the door quick... sick kid.

No problem.  Good luck!

> Code works AFAIK, just needs better docs and travis hooked up. I tested py27 and py34 locally. 

Doing that now.

**Comment by daf** [comment]
> For CC, we need to abandon this library...

@lukecampbell I rez'd my CC nowicken branch earlier today and shockingly have it running tests ok, merged up with master.  Will be prepping PR tomorrow.

**Comment by daf** [comment]
@kwilcox it broke Wicken, but I think it was just the removal of those netcdf imports combined with a * import in Wicken.  I'll fix it there.

**Comment by lukecampbell** [comment]
@daf you're my hero.

**Pull request merged**
